"""create faces schema

Revision ID: a60bca73329a
Revises: 
Create Date: 2025-06-04 18:58:07.048082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = 'a60bca73329a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('path')
                    )
    op.create_table('embeddings',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('image_id', sa.Integer(), nullable=False),
                    sa.Column('x', sa.Float(), nullable=False),
                    sa.Column('y', sa.Float(), nullable=False),
                    sa.Column('w', sa.Float(), nullable=False),
                    sa.Column('h', sa.Float(), nullable=False),
                    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(
                        dim=512), nullable=False),
                    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_embeddings_vector_ivf', 'embeddings', [
                    'vector'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100})
    op.create_table('participants',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('image_id', sa.Integer(), nullable=False),
                    sa.Column('embedding_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['embedding_id'], ['embeddings.id'], ),
                    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_index('idx_embeddings_vector_ivf', table_name='embeddings',
                  postgresql_using='ivfflat', postgresql_with={'lists': 100})
    op.drop_table('embeddings')
    op.drop_table('images')
    # ### end Alembic commands ###
